LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

ENGINE_PATH := ../

LOCAL_MODULE := main
LOCAL_MODULE_FILENAME := libMain

LOCAL_ARM_MODE	:= arm

LOCAL_CPPFLAGS += -fpermissive
LOCAL_CPPFLAGS += -fexceptions
LOCAL_CFLAGS += -w
LOCAL_CFLAGS += -O2
LOCAL_CFLAGS += -fPIC
LOCAL_CFLAGS += -frtti
LOCAL_CFLAGS += -DPIC
LOCAL_CFLAGS += -DDARWIN_NO_CARBON
LOCAL_CFLAGS += -D_ANDROID
LOCAL_CFLAGS += -DPOST_FROYO
LOCAL_CFLAGS += -DAL_ALEXT_PROTOTYPES
LOCAL_CFLAGS += -D_DEBUG
LOCAL_CFLAGS += -DTU_CONFIG_VERBOSE

LOCAL_C_INCLUDES += \
$(LOCAL_PATH)/$(ENGINE_PATH) \

LOCAL_SRC_FILES := \
Main.cpp \
IrisWorldDemo.cpp \
ShaderDemo.cpp \
\
$(ENGINE_PATH)/JNIBridge.cpp \

LOCAL_SHARED_LIBRARIES := Iris
LOCAL_LDLIBS := -llog -lGLESv1_CM -landroid -lz

include $(BUILD_SHARED_LIBRARY)